# Data Preprocessing

<h1>data acquisition and cleaning</h1>

In [4]:
# load project libraries
import numpy as np
import pandas as pd

In [5]:
# load data into dataframe to easy access and manipulation
forest_fire_df = pd.read_csv('forestfires.csv')
# display the first five rows in dataframe
forest_fire_df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [6]:
# dataset description 
desc = open('forestfires.names','r')
desc = str(desc.readlines())
desc = eval(desc)

In [9]:
# finding missing values
forest_fire_df.replace("None",np.nan,inplace = True)

In [10]:
missing_data = forest_fire_df.isnull()

In [12]:
missing_data.head()

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
# counting missing values
for col in mis.columns.values.tolist():
    print(col)
    print(forest_fire_df[col].value_counts())
    print("")

X
4    91
6    86
2    73
8    61
7    60
3    55
1    48
5    30
9    13
Name: X, dtype: int64

Y
4    203
5    125
6     74
3     64
2     44
9      6
8      1
Name: Y, dtype: int64

month
aug    184
sep    172
mar     54
jul     32
feb     20
jun     17
oct     15
apr      9
dec      9
may      2
jan      2
nov      1
Name: month, dtype: int64

day
sun    95
fri    85
sat    84
mon    74
tue    64
thu    61
wed    54
Name: day, dtype: int64

FFMC
91.6    28
92.1    28
91.0    22
91.7    19
93.7    16
92.4    16
92.5    15
94.8    14
90.2    12
90.1    12
92.9    12
91.4    11
91.2    11
93.5    11
91.1    10
94.3     9
90.9     9
92.2     9
91.5     9
91.8     9
90.6     8
95.2     7
93.1     7
93.4     6
96.1     6
92.3     6
92.8     6
90.3     6
91.9     6
90.7     5
        ..
83.9     2
88.9     1
69.0     1
85.2     1
86.2     1
88.0     1
83.0     1
86.9     1
85.0     1
86.8     1
18.7     1
94.0     1
95.0     1
87.5     1
91.3     1
92.7     1
81.9     1
94.4     1
68.2     1
53.4     1
84.2     1
85.6     1
85.8     1
95.8     1
88.3     1
50.4     1
82.1     1
86.3     1
85.1     1
87.1     1
Name: FFMC, Length: 106, dtype: int64

DMC
99.0     10
129.5     9
142.4     8
231.1     8
137.0     7
126.5     7
108.4     7
108.3     7
35.8      7
117.9     6
102.3     6
25.4      6
149.3     6
85.1      6
181.1     6
111.2     6
152.6     6
145.4     6
51.3      6
99.6      6
139.4     6
104.2     5
121.1     5
166.9     5
122.0     5
52.2      5
157.3     5
141.3     5
181.3     5
130.1     5
         ..
6.8       1
26.7      1
88.8      1
55.2      1
7.3       1
23.3      1
291.3     1
15.1      1
196.8     1
26.2      1
75.6      1
27.9      1
27.4      1
127.1     1
62.3      1
88.9      1
103.8     1
1.1       1
92.1      1
8.7       1
238.2     1
26.4      1
6.6       1
110.9     1
253.6     1
4.6       1
24.9      1
133.6     1
96.3      1
3.2       1
Name: DMC, Length: 215, dtype: int64

DC
745.3    10
692.6     9
698.6     8
601.4     8
692.3     8
715.1     8
647.1     7
686.5     7
706.4     7
80.8      7
764.0     7
631.2     6
668.0     6
751.5     6
654.1     6
658.2     6
671.2     6
728.6     6
789.7     5
605.8     5
102.2     5
699.6     5
753.8     5
752.6     5
807.1     5
613.0     5
349.7     5
474.9     5
783.5     5
674.4     5
         ..
844.0     1
41.1      1
9.3       1
424.1     1
706.8     1
706.6     1
680.9     1
442.9     1
368.3     1
694.8     1
252.6     1
83.7      1
18.7      1
41.6      1
366.7     1
682.6     1
316.7     1
520.5     1
607.1     1
466.3     1
97.1      1
495.6     1
106.7     1
48.3      1
52.8      1
730.6     1
431.6     1
74.3      1
313.4     1
537.4     1
Name: DC, Length: 219, dtype: int64

ISI
9.6     23
7.1     21
6.3     20
7.0     17
8.4     17
6.2     16
9.2     15
7.5     14
8.1     12
7.8     12
9.0     12
14.3    12
8.5      9
10.6     8
12.5     8
8.9      7
17.0     7
8.6      7
9.9      7
13.9     7
2.6      6
1.9      6
6.8      6
15.9     6
5.0      6
12.2     6
13.5     5
8.8      5
3.8      5
10.2     5
        ..
2.0      1
13.0     1
0.0      1
0.7      1
5.4      1
2.2      1
21.3     1
9.8      1
3.4      1
1.8      1
8.3      1
14.4     1
6.6      1
12.9     1
16.7     1
11.6     1
9.4      1
16.3     1
9.7      1
3.3      1
12.7     1
2.3      1
1.1      1
22.6     1
10.8     1
7.3      1
12.1     1
14.6     1
56.1     1
22.7     1
Name: ISI, Length: 119, dtype: int64

temp
17.4    8
19.6    8
15.4    7
20.6    7
23.4    6
21.6    6
17.8    6
18.9    6
20.7    6
19.1    6
20.1    6
15.9    6
4.6     6
15.2    6
21.9    6
20.4    6
19.3    6
18.2    6
16.8    6
20.8    6
24.3    5
24.2    5
26.4    5
23.3    5
24.1    5
19.4    5
5.1     5
22.8    5
17.6    5
17.7    5
       ..
5.2     1
33.1    1
13.2    1
11.7    1
16.9    1
9.8     1
12.8    1
27.6    1
29.3    1
27.7    1
30.6    1
27.4    1
14.9    1
18.1    1
13.1    1
11.4    1
10.4    1
28.6    1
2.2     1
12.3    1
29.2    1
12.6    1
25.6    1
26.3    1
28.2    1
29.6    1
8.7     1
25.7    1
31.0    1
4.8     1
Name: temp, Length: 192, dtype: int64

RH
27     33
39     24
35     20
43     17
42     17
45     16
34     16
40     15
33     15
46     14
24     13
44     13
32     12
51     12
28     11
41     11
38     11
53     11
25     10
54      9
47      9
36      9
29      9
50      8
59      8
64      8
37      8
56      7
31      7
48      7
       ..
75      4
63      4
77      4
65      3
79      3
52      3
67      3
61      3
62      3
72      3
15      2
74      2
82      2
86      2
68      2
90      2
99      1
94      1
17      1
18      1
97      1
20      1
96      1
87      1
88      1
84      1
80      1
76      1
69      1
100     1
Name: RH, Length: 75, dtype: int64

wind
2.2    53
3.1    53
4.0    51
4.9    48
2.7    44
4.5    41
5.4    41
3.6    40
1.8    31
5.8    24
6.3    19
7.6    14
1.3    14
0.9    13
6.7     8
8.5     8
8.0     5
7.2     4
9.4     4
8.9     1
0.4     1
Name: wind, dtype: int64

rain
0.0    509
0.8      2
0.2      2
0.4      1
6.4      1
1.4      1
1.0      1
Name: rain, dtype: int64

area
0.00     247
1.94       3
3.71       2
0.90       2
1.95       2
2.14       2
2.18       2
1.56       2
9.96       2
28.66      2
1.46       2
0.68       2
0.43       2
1.64       2
6.43       2
9.27       2
0.52       2
1.75       2
11.06      2
1.63       2
17.20      1
48.55      1
0.95       1
0.77       1
11.19      1
15.64      1
2.64       1
3.52       1
38.48      1
5.39       1
        ...
1.61       1
1.07       1
6.38       1
5.86       1
3.19       1
11.16      1
8.85       1
86.45      1
5.18       1
30.18      1
2.01       1
1.01       1
20.03      1
0.79       1
49.59      1
4.41       1
7.02       1
0.71       1
9.41       1
0.09       1
3.32       1
11.53      1
5.55       1
3.20       1
4.88       1
1.26       1
2.44       1
2.03       1
2.21       1
24.24      1
Name: area, Length: 251, dtype: int64